### ISSUE TITLE
Non-poll creators see "Fetching poll" permanently

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#120]
As a regular visitor, no authentication, on my phone and laptop, I tried to vote in this poll:
https://rankit.skelpo.com/vote/rDZnWYOUBh5BbaSUvF1b

It is Published and set to Open, Accepting Votes, so I should be seeing the "Vote" page. But when I try to view the vote page on my phone, I get a "Fetching poll" message permanently. I checked it on wifi and data, so I know it's not a connection issue.

Next, I tried to vote in this poll, which is Closed:
https://rankit.skelpo.com/vote/11P9PU0oBcVS16P1fww5

It redirects me to https://rankit.skelpo.com/results/11P9PU0oBcVS16P1fww5/summary, which is good. However, on that page I also see a "Fetching poll" message permanently.

**Comment by proggeramlug** [comment]
Should be fixed!

**Comment by ggordn3r** [comment]
Issue still persists for me on this poll:
https://rankit.skelpo.com/results/11P9PU0oBcVS16P1fww5/summary

**Comment by proggeramlug** [comment]
Good find - fixed!

**Comment by ggordn3r** [comment]
Hmm... now we're back to the situation I had at the beginning. On phone and laptop without authentication I am seeing "Fetching poll" permanently.

**Comment by proggeramlug** [comment]
Reload, I just verified through a private browser window that the original issue has been fixed. However I think the problem you are facing is introduce because your devices have some (normal) caches that are not using th enewest version.

**Comment by ggordn3r** [comment]
I force refreshed the cache in my regular window and opened up a private window as a normal visitor and still saw this issue. Screenshot below.

![image](https://user-images.githubusercontent.com/10144772/81028807-e3499680-8e50-11ea-8b2c-f18e12eaea71.png)

**Comment by proggeramlug** [comment]
Oldest error in the history of programming :D Your link above is not the same poll as the one in your screenshot. I typed the ID from your screenshot and was finally able to reproduce and then fix the problem :)

Good find!

**Comment by ggordn3r** [comment]
Whew! Glad you figured it out. Just checked and both the ones I tested before are working as expected.
