### ISSUE TITLE
Poll settings for other users' polls no longer appear for admins

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#136]
See screenshot. I went to "manage polls" as an admin and chose this one:
https://rankit.vote/polls/2dRIuBr22njWRKVXGp7U

Expected behavior is to open the poll management page and allow me to update the settings as if I am the poll creator. This was the case before. Now, the page does not load at all. See screenshots:

![Screenshot (354)](https://user-images.githubusercontent.com/10144772/86318382-c8509400-bbff-11ea-9fb6-785498e784f9.png)

With Console open:

![Screenshot (355)](https://user-images.githubusercontent.com/10144772/86318421-dc949100-bbff-11ea-8d43-567eb0a1ac5e.png)

**Comment by proggeramlug** [comment]
Fixed!

**Comment by ggordn3r** [comment]
Hmm, just tried this again by logging in with trey@koios.co on rankit.skelpo.com, still seeing the same blank screen. I chose this poll this time: https://rankit.vote/polls/00eGvMCcol8N8jIjv1b2.

**Comment by proggeramlug** [comment]
Hm try again, it works for me (tested on rankit.skelpo.com )

**Comment by ggordn3r** [comment]
What's causing the slow server response? I can't be sure this is fixed because the page hasn't finished loading after 8 minutes.

I retested on https://rankit.vote/polls/00eGvMCcol8N8jIjv1b2 with Network open in dev tools. Five minutes later, the page is still making calls one-by-one to the server. I've pasted a few of them below with their response times. My download speed is running at 117mbps, so it's definitely a server issue.

Request URL: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Frankit-vote%2Fdatabases%2F(default)&gsessionid=8Emnljx8ypYTsUs9CRrFEj7oNOVafoCJE71F8yl_0Tw&VER=8&RID=rpc&SID=P7OJ6xFzfrSKMFNvNalSgw&CI=0&AID=0&TYPE=xmlhttp&zx=bfo9dvd696lj&t=1
GET took over 45 seconds

Request URL: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Frankit-vote%2Fdatabases%2F(default)&gsessionid=8Emnljx8ypYTsUs9CRrFEj7oNOVafoCJE71F8yl_0Tw&VER=8&RID=rpc&SID=P7OJ6xFzfrSKMFNvNalSgw&CI=0&AID=15&TYPE=xmlhttp&zx=qry80kfyek6&t=1
GET took 1.3 mins

Request URL: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Frankit-vote%2Fdatabases%2F(default)&gsessionid=8Emnljx8ypYTsUs9CRrFEj7oNOVafoCJE71F8yl_0Tw&VER=8&RID=rpc&SID=P7OJ6xFzfrSKMFNvNalSgw&CI=0&AID=15&TYPE=xmlhttp&zx=qry80kfyek6&t=1
GET took 1.0 mins

Do I need to open a new issue for this speed problem?

**Comment by proggeramlug** [comment]
I've been wrestling with this performance issue for days now, it seems to be mainly up to Google. The life version of rankit is not noticably faster than the dev version and it seems to be very sporadic. Can you test today (sunday) as well as monday/tuesday and see if there are any changes?

I have tightened a few screws and it is working better for me now. The bug you are seeing is also part of this weird firebase update. The cononection that is still open after 8 minutes is what caused our server to take forever to return the site - Google  is keeping a connection open . That said, it is fixed in the newet release: https://rankit.skelpo.com/polls/00eGvMCcol8N8jIjv1b2
If the page remains empty after 10 seconds you are likely not looged in.

Check it out!

**Comment by ggordn3r** [comment]
Ok, this is working, so I'm going to close it. Just one last question: would Stephen know anything about Firebase performance? If so, have you asked him?

**Comment by proggeramlug** [comment]
I have not yet but I can today ...

**Comment by proggeramlug** [comment]
Stephen and I just talked on the phone, he doesn't think Firebase would be the cause for any issues.

That said with my most recent fixes things should look much better, have you tested that part yet?

**Comment by ggordn3r** [comment]
Yes, tested and this is much snappier for me now. Closing.
