### ISSUE TITLE
Results view: distinguish floating buttons more clearly

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#140]
See 2 screenshots.

1) Intensify the shadow on mobile and desktop to make it clearer that the buttons are an overlay:
![Screenshot (363)](https://user-images.githubusercontent.com/10144772/87592657-3ee99900-c6b8-11ea-8a11-d6a7e2284a3b.png)

2) On desktop, style the buttons oval, right aligned, and no wider than the graph, as below. White button border is 1px and uses Bar Color (custom or default). 
![Screenshot (364)](https://user-images.githubusercontent.com/10144772/87592813-7bb59000-c6b8-11ea-9743-3b12bb2d5009.png)

**Comment by proggeramlug** [comment]
Done, check it out!

**Comment by ggordn3r** [comment]
This change appears to have introduced some odd alignment issues. See the screenshots below. Expected behavior is that buttons appearing alone are always in the _right_ position, but now it seems they are appearing on the left:

This is wrong because the button is appearing on the far-left, not the far-right:
![Screenshot (376)](https://user-images.githubusercontent.com/10144772/88575014-39257900-d011-11ea-9864-be6978a4f14b.png)

The buttons work correctly when there are more than one, so the issue appears to be limited to cases when there is only 1 button:
![Screenshot (377)](https://user-images.githubusercontent.com/10144772/88575252-96b9c580-d011-11ea-8fe5-32b81608a096.png)

The issue also appears with other classes of buttons:
![Screenshot (375)](https://user-images.githubusercontent.com/10144772/88575347-bb15a200-d011-11ea-9b75-13cb9bfc3f4f.png)

**Comment by proggeramlug** [comment]
Fixed!

**Comment by ggordn3r** [comment]
2 tweaks:

1) This still looks off on mobile. See screenshot:
![Screenshot (387)](https://user-images.githubusercontent.com/10144772/88841283-ba187800-d1ab-11ea-822f-cceefb7ea652.png)

2) On desktop, can you give this the same oval shape and right alignment as the results buttons? As is, the giant field of pink drowns out the "Take Action" button. 
![Screenshot (388)](https://user-images.githubusercontent.com/10144772/88841343-d5838300-d1ab-11ea-8687-56c350754a89.png)

**Comment by proggeramlug** [comment]
All fixed!

**Comment by ggordn3r** [comment]
One last tweak. "See Results by Round" should fill the whole button space on mobile:

![Screenshot_20200806-130402](https://user-images.githubusercontent.com/10144772/89561625-c6718600-d7e6-11ea-911f-003e065f4556.png)

**Comment by proggeramlug** [comment]
Done!

**Comment by ggordn3r** [comment]
The fix appears to have introduced a new bug where the button is cut off on mobile. If I scroll up the button scrolls as well:

![Screenshot_20200812-095227](https://user-images.githubusercontent.com/10144772/90023640-f3f47e80-dc81-11ea-9e4c-0ec2fbe48a9b.png)

**Comment by proggeramlug** [comment]
Fixed!

**Comment by ggordn3r** [comment]
Hmm... still seeing it on my phone. I hard refreshed the page and checked in an incognito window just to make sure.
