### ISSUE TITLE
Call-to-action page extends beyond screen width on mobile

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#78]
As described, the page doesn't "fit" in the view. The user can scroll left and right. Screenshot shows the view at the furthest right extreme. Looks like it might be an issue with the width of the purple section vs. the top white section.

Confirmed on iPhone and Android by 2 separate testers.

![Screenshot_20191015-144824_Chrome](https://user-images.githubusercontent.com/10144772/66860404-2565c600-ef5b-11e9-8731-607ac1e3bac7.jpg)

**Comment by iambateman** [comment]
This is addressed in the next push.

**Comment by ggordn3r** [comment]
Confirmed, this is fixed.

**Comment by ggordn3r** [comment]
Still seeing this on my phone on rankit.vote as of 10/23 at 12:46pm. See screenshot.

https://rankit.vote/vote/41vxTFg2QyaK9mlzX2Wx/success

![Screenshot_20191023-124523_Chrome](https://user-images.githubusercontent.com/10144772/67415579-4a79ba80-f593-11e9-8a0f-59d334ab342b.jpg)

**Comment by iambateman** [comment]
Yep. Turns out I pushed code into a vacuum and just realized today. Sorry. We'll need to confirm tomorrow, but it should be fixed then!
